#!/usr/bin/env bash

COMMANDS=$(cat _terraform_cmds | grep "^function" | awk '{print $2}' | grep -v "^_" | tr "\n" " " )
readonly STACK_FROM_INFRA="stack"
readonly CONFIG_FROM_STACK="../../../../../../terraform-config/azure"
APPLY_PLAN="apply.tfplan"
DESTROY_PLAN="destroy.tfplan"

function _debug {
    echo "${SUBSCRIPTION_ID}" "${ENVIRONMENT}" "${LOCATION}" "${COMPONENT}" "${COMMAND}"
}

function _set_remote_state {
    cd "${SUBSCRIPTION_ID}/${STACK_FROM_INFRA}/${COMPONENT}" || exit
    terraform init -upgrade \
        -input=false \
        -backend-config="storage_account_name=7f967551eaceterraform" \
        -backend-config="key=${SUBSCRIPTION_ID}/${LOCATION}/${ENVIRONMENT}/${COMPONENT}/terraform.tfstate" \
        -backend-config="container_name=terraform-state" \
        -backend-config="resource_group_name=genesis_resource_group"
}

function get {
    _set_remote_state
    terraform get "$@"
}

function plan {
    _set_remote_state
    terraform plan \
        -var-file "${CONFIG_FROM_STACK}/vars/common.tfvars.json" \
        -var-file "${CONFIG_FROM_STACK}/vars/${SUBSCRIPTION_ID}/common.tfvars.json" \
        -var-file "${CONFIG_FROM_STACK}/vars/${SUBSCRIPTION_ID}/${LOCATION}/common.tfvars.json" \
        -var-file "${CONFIG_FROM_STACK}/vars/${SUBSCRIPTION_ID}/${LOCATION}/${ENVIRONMENT}/common.tfvars.json" \
        -var-file "${CONFIG_FROM_STACK}/vars/${SUBSCRIPTION_ID}/${LOCATION}/${ENVIRONMENT}/${COMPONENT}/config.tfvars.json" \
        -out "${APPLY_PLAN}" \
        "$@"
}

function apply {
    _set_remote_state
    terraform apply "$@" "${APPLY_PLAN}"
}

function plan_destroy {
    _set_remote_state
    terraform plan -destroy \
        -var-file "${CONFIG_FROM_STACK}/vars/common.tfvars.json" \
        -var-file "${CONFIG_FROM_STACK}/vars/${SUBSCRIPTION_ID}/common.tfvars.json" \
        -var-file "${CONFIG_FROM_STACK}/vars/${SUBSCRIPTION_ID}/${LOCATION}/common.tfvars.json" \
        -var-file "${CONFIG_FROM_STACK}/vars/${SUBSCRIPTION_ID}/${LOCATION}/${ENVIRONMENT}/common.tfvars.json" \
        -var-file "${CONFIG_FROM_STACK}/vars/${SUBSCRIPTION_ID}/${LOCATION}/${ENVIRONMENT}/${COMPONENT}/config.tfvars.json" \
        -out "${DESTROY_PLAN}" \
        "$@"
}

function destroy {
    _set_remote_state
    terraform apply "$@" "${DESTROY_PLAN}"
}

function show_state {
    _set_remote_state
    terraform show "$@" terraform.tfstate
}