name: 'IaC'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.4
    
    # Install the latest version of Packer CLI
    - name: Setup Packer
      uses: hashicorp-contrib/setup-packer@v1.0.0
      with:
        packer-version: 1.6.6

    # Packer build
    - name: Build Golden Image - Packer
      run: cd packer && packer build -var image-identifier=$(git rev-parse --short=5 HEAD) -var azure-subscription-id=${{ secrets.ARM_SUBSCRIPTION_ID }} -var azure-client-id=${{ secrets.ARM_CLIENT_ID }}  -var azure-client-secret=${{ secrets.ARM_CLIENT_SECRET }} -var azure-tenant-id=${{ secrets.ARM_TENANT_ID }} -var-file=windows-variables.json windows-2019-iis.json
